export const DEPARTMENT_ACTIONS_TYPES = {
  GET_DEPARTMENTS_ACTION: 'GET_DEPARTMENTS_ACTION',
  GET_DEPARTMENTS_FAILED: 'GET_DEPARTMENTS_FAILED',
  GET_DEPARTMENTS_SUCCESS: 'GET_DEPARTMENTS_SUCCESS',
  GET_DEPARTMENT_ACTION: 'GET_DEPARTMENT_ACTION',
  GET_DEPARTMENT_FAILED: 'GET_DEPARTMENT_FAILED',
  GET_DEPARTMENT_SUCCESS: 'GET_DEPARTMENT_SUCCESS',
  CREATE_DEPARTMENT_ACTION: 'CREATE_DEPARTMENT_ACTION',
  CREATE_DEPARTMENT_FAILED: 'CREATE_DEPARTMENT_FAILED',
  CREATE_DEPARTMENT_SUCCESS: 'CREATE_DEPARTMENT_SUCCESS',
  DELETE_DEPARTMENT_ACTION: 'DELETE_DEPARTMENT_ACTION',
  DELETE_DEPARTMENT_FAILED: 'DELETE_DEPARTMENT_FAILED',
  DELETE_DEPARTMENT_SUCCESS: 'DELETE_DEPARTMENT_SUCCESS',
};